### ISSUE TITLE
How do you do it faster?

### ISSUE THREAD

**Issue by yakovw** [sandrohanea/whisper.net#91] opened 2023-07-02 21:33 UTC
I'm looking for ways to make the transcription faster?
This library is excellent and I really enjoy it, but the transcription takes me a long time.
I have a powerful CPU
And a powerful GPU
And still it's very slow, it doesn't use at all the CPU it could use, certainly not the GPU
Is there a way I can make it work faster?

**Comment by Van-Dame** [comment] 2023-07-12 00:15
I found that using `.WithSpeedUp2x()` and `.WithThreads(16)` speeds up transcribing by ~3x. YMMV though.

**Comment by Sing303** [comment] 2023-08-29 12:22
When using tiny / base / small models it doesn't use all 32 threads, even if I specify all 32 threads. Is this the way it should be or can I speed it up?

**Comment by sandrohanea** [comment] 2023-09-02 13:23
Closing as a duplicate of https://github.com/sandrohanea/whisper.net/issues/89

**Closed by sandrohanea** 2023-09-02 13:23 UTC
