### ISSUE TITLE
Illegal Instructions - AVX2

### ISSUE THREAD

**Issue by RoryMcHughh** [sandrohanea/whisper.net#153] opened 2024-01-16 22:50 UTC
Does whisper.net only work with AVX2 processors? 

I have two machines one with AVX2 on windows server 2019 and one with AVX1 on windows 10 and whisper is only working on the machine with avx2. Both machines are x64.

**Comment by sandrohanea** [comment] 2024-02-03 15:31
Hello @RoryMcHughh ,
Unfortunately, the default build of Whisper.net.Runtime is including AVX and AVX2 instructions.

This is a duplicate of: https://github.com/sandrohanea/whisper.net/issues/110

You can build the native library without AVX or AVX2 using `WHISPER_NO_AVX` and / or `WHISPER_NO_AVX2` https://github.com/ggerganov/whisper.cpp/blob/447d49530c9af41fe24f2ae510f452903dba330d/CMakeLists.txt#L58C8-L58C22

**Closed by sandrohanea** 2024-02-03 15:31 UTC
