### ISSUE TITLE
Unable to run version 1.7.0 on linux

### ISSUE THREAD

**Issue by TomasEkeli** [sandrohanea/whisper.net#222] opened 2024-10-15 19:58 UTC
Running in an Ubuntu devcontainer on a windows host. This has been tested on both windows 10 and 11.

I tried to upgrade my project to use the new version 1.7.0, but get an exception every time whisper should have loaded.

    Unable to load shared library 'whisper' or one of its dependencies

So, I tried with one of the examples from this repository: `examples/Simple`  - it gets the same error.

Reproduction is to go to my [fork of this project](https://github.com/TomasEkeli/whisper.net) and open it in vscode in the defined devcontainer (it will ask you to on first open). This devcontainer takes a little while to start, as it downloads cmake and makes whisper.cpp on creation, but that's not relevant to the test.

After the devcontainer has started: cd into `examples/Simple`, copy `kennedy.wav` from `tests/TestData` and do `dotnet run --framework net8..0` to recreate the exception.

Changing the versions in `examples/Simple/Simple.csproj` to 1.5.0 makes the example run completely fine with no exception.

**Comment by TomasEkeli** [comment] 2024-10-16 20:53
i have now tried it with 1.7.1-preview1. This works, with cpu (yay!), but it seems a lot slower?

Anyway - when i built it with the cuda runtime referenced and ran it on a machine without cuda installed (without a gpu at all) i got this error: 

```
     System.DllNotFoundException: Unable to load shared library '/workspaces/transcription/src/web/bin/Debug/net8.0/runtimes/cuda/linux-x64/libggml.so' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
      /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.8//workspaces/transcription/src/web/bin/Debug/net8.0/runtimes/cuda/linux-x64/libggml.so: cannot open shared object file: No such file or directory
      libcudart.so.12: cannot open shared object file: No such file or directory
      
         at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
         at Whisper.net.LibraryLoader.UniversalLibraryLoader.OpenLibrary(String fileName, Boolean global)
         at Whisper.net.LibraryLoader.NativeLibraryLoader.LoadLibraryComponent()
         at Whisper.net.LibraryLoader.NativeLibraryLoader.LoadNativeLibrary()
         at Whisper.net.WhisperFactory.<>c.<.cctor>b__9_0()
         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
         at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
         at System.Lazy`1.CreateValue()
         at Whisper.net.WhisperFactory..ctor(IWhisperProcessorModelLoader loader, Boolean delayInit)
         at Whisper.net.WhisperFactory.FromPath(String path, Boolean delayInitialization)
```

does this mean that we still have to build separate versions with and without gpu-support?

**Comment by sandrohanea** [comment] 2024-10-16 21:03
I will need to run some tests on v1.5.0 vs v1.7.1 before releasing to check the performance on linux hosts. 

Regarding the issue with the Cuda runtime on a machine without GPU, it was also reported here: https://github.com/sandrohanea/whisper.net/pull/224
A little different there as the CPU was automatically used by the Cuda Runtime machine (as probably they had the driver installed).

However, in both cases (with or without the driver installed), it should be fixed into https://github.com/sandrohanea/whisper.net/pull/225 but it is not yet available in any nuget package.


Same issues might reproduce with other runtimes installed that are not available, but will prepare some fixes for these cases and ensure proper fallback for each scenario.

**Comment by sandrohanea** [comment] 2024-10-17 19:48
>This works, with cpu (yay!), but it seems a lot slower?
> 

Indeed, 1.7.1-preview1 was a lot slower than 1.5.0 and  after inversigation the reason was a change in the native build that changed the native optimizations to be disabled by default if building for other systems (CMAKE_CROSSCOMPILING) :
https://github.com/ggerganov/whisper.cpp/commit/ab8ec9e9402839112ba7e98bbca7118a87c4153e

Once I activated these, the newer version will be even faster than 1.5.0 (as different optimizations were done in the meantime in ggml libs and whisper) 
Will be fixed by: https://github.com/sandrohanea/whisper.net/pull/229

Also added `WhisperFactory.GetRuntimeInfo()` method that exposes the native runtime `whisper_print_system_info` for finding all the optimizations and info about the loaded runtime.

**Comment by sandrohanea** [comment] 2024-10-17 22:08
v1.7.1 is live with fixes for the issues mentioned in this thread

**Closed by sandrohanea** 2024-10-17 22:08 UTC

**Comment by TomasEkeli** [comment] 2024-10-18 20:11
wonderful, can't wait to try it out!
